2023-04-19 10:07:25,102 INFO    Thread-1940 (_run_job):16112 [wandb_setup.py:_flush():76] Configure stats pid to 16112
2023-04-19 10:07:25,102 INFO    Thread-1940 (_run_job):16112 [wandb_setup.py:_flush():76] Loading settings from C:\Users\cosmi\.config\wandb\settings
2023-04-19 10:07:25,102 INFO    Thread-1940 (_run_job):16112 [wandb_setup.py:_flush():76] Loading settings from C:\MyDocuments\Disertatie\segments\wandb_visualization\wandb\settings
2023-04-19 10:07:25,102 INFO    Thread-1940 (_run_job):16112 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'entity': 'cosminaionut', 'project': 'Defect-Detection-Sweep', 'root_dir': 'C:\\MyDocuments\\Disertatie\\segments\\wandb_visualization', 'run_id': '1ujlb0qk', 'sweep_param_path': 'C:\\MyDocuments\\Disertatie\\segments\\wandb_visualization\\wandb\\sweep-uxdb9ain\\config-1ujlb0qk.yaml', 'sweep_id': 'uxdb9ain'}
2023-04-19 10:07:25,118 INFO    Thread-1940 (_run_job):16112 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-04-19 10:07:25,118 INFO    Thread-1940 (_run_job):16112 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'sweeps_configuration.py', 'program': 'C:\\MyDocuments\\Disertatie\\segments\\wandb_visualization\\sweeps_configuration.py'}
2023-04-19 10:07:25,118 INFO    Thread-1940 (_run_job):16112 [wandb_init.py:_log_setup():507] Logging user logs to C:\MyDocuments\Disertatie\segments\wandb_visualization\wandb\run-20230419_100725-1ujlb0qk\logs\debug.log
2023-04-19 10:07:25,118 INFO    Thread-1940 (_run_job):16112 [wandb_init.py:_log_setup():508] Logging internal logs to C:\MyDocuments\Disertatie\segments\wandb_visualization\wandb\run-20230419_100725-1ujlb0qk\logs\debug-internal.log
2023-04-19 10:07:25,118 INFO    Thread-1940 (_run_job):16112 [wandb_init.py:init():547] calling init triggers
2023-04-19 10:07:25,118 INFO    Thread-1940 (_run_job):16112 [wandb_init.py:init():554] wandb.init called with sweep_config: {'batch_size': 32, 'epochs': 200, 'hidden_layer_size': [20], 'learning_rate': 0.03368788067131874, 'monitor': 'val_loss', 'optimizer': 'adam', 'patience': 3}
config: {}
2023-04-19 10:07:25,118 INFO    Thread-1940 (_run_job):16112 [wandb_init.py:init():595] starting backend
2023-04-19 10:07:25,118 INFO    Thread-1940 (_run_job):16112 [wandb_init.py:init():599] setting up manager
2023-04-19 10:07:25,118 INFO    Thread-1940 (_run_job):16112 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-04-19 10:07:25,118 INFO    Thread-1940 (_run_job):16112 [wandb_init.py:init():605] backend started and connected
2023-04-19 10:07:25,134 INFO    Thread-1940 (_run_job):16112 [wandb_run.py:_config_callback():1285] config_cb None None {'batch_size': 32, 'epochs': 200, 'hidden_layer_size': [20], 'learning_rate': 0.03368788067131874, 'monitor': 'val_loss', 'optimizer': 'adam', 'patience': 3}
2023-04-19 10:07:25,134 INFO    Thread-1940 (_run_job):16112 [wandb_init.py:init():695] updated telemetry
2023-04-19 10:07:25,134 INFO    Thread-1940 (_run_job):16112 [wandb_init.py:init():732] communicating run to backend with 60.0 second timeout
2023-04-19 10:07:25,585 INFO    Thread-1940 (_run_job):16112 [wandb_run.py:_on_init():2176] communicating current version
2023-04-19 10:07:25,773 INFO    Thread-1940 (_run_job):16112 [wandb_run.py:_on_init():2185] got version response 
2023-04-19 10:07:25,773 INFO    Thread-1940 (_run_job):16112 [wandb_init.py:init():782] starting run threads in backend
2023-04-19 10:07:26,983 INFO    Thread-1940 (_run_job):16112 [wandb_run.py:_console_start():2157] atexit reg
2023-04-19 10:07:26,983 INFO    Thread-1940 (_run_job):16112 [wandb_run.py:_redirect():2012] redirect: SettingsConsole.WRAP_RAW
2023-04-19 10:07:26,983 INFO    Thread-1940 (_run_job):16112 [wandb_run.py:_redirect():2077] Wrapping output streams.
2023-04-19 10:07:26,983 INFO    Thread-1940 (_run_job):16112 [wandb_run.py:_redirect():2102] Redirects installed.
2023-04-19 10:07:26,983 INFO    Thread-1940 (_run_job):16112 [wandb_init.py:init():824] run started, returning control to user process
2023-04-19 10:10:11,512 ERROR   Thread-6 (_heartbeat):16112 [internal_api.py:execute():288] 500 response executing GraphQL.
2023-04-19 10:10:11,512 ERROR   Thread-6 (_heartbeat):16112 [internal_api.py:execute():289] {"errors":[{"message":"An internal error occurred. Please contact support.","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
2023-04-19 10:12:20,224 INFO    Thread-1940 (_run_job):16112 [wandb_run.py:_finish():1892] finishing run cosminaionut/Defect-Detection-Sweep/1ujlb0qk
2023-04-19 10:12:20,224 INFO    Thread-1940 (_run_job):16112 [wandb_run.py:_atexit_cleanup():2126] got exitcode: 0
2023-04-19 10:12:20,224 INFO    Thread-1940 (_run_job):16112 [wandb_run.py:_restore():2109] restore
2023-04-19 10:12:20,224 INFO    Thread-1940 (_run_job):16112 [wandb_run.py:_restore():2115] restore done
2023-04-19 10:13:09,702 ERROR   Thread-6 (_heartbeat):16112 [internal_api.py:execute():288] 500 response executing GraphQL.
2023-04-19 10:13:09,702 ERROR   Thread-6 (_heartbeat):16112 [internal_api.py:execute():289] {"error":"An internal error occurred. Please contact support."}
